baseURL = "https://awesome-rosalind-68f1b3.netlify.app/"
languageCode = "en-us"
title = "Luc Blassel"
copyright = "Luc Blassel"
theme = "hagan"

[params]
  owner = "Luc Blassel"
  keywords = ["PhD. Student", "Computational Biology", "machine learning"]
  gravatarId = "d885cad4ccb230040b32a58d35a0dfda"
  getFormEndpoint = "https://getform.io/f/7b67ea7b-ca18-43b0-a2b5-c9b35b57581e"
  reCaptchaKey = "6Lf49iccAAAAAP2_whsMpa8hPKk-3Zy_BbiIx2_y"

[markup]
  [markup.highlight]
    style = 'github'
    lineNos = true
    lineNumbersInTable = true

[menu]

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5

  [[menu.socials]]
    name = "Github"
    url = "https://github.com/lucblassel"
    pre = '<i class="fab fa-github"></i>'

  [[menu.socials]]
    name = "Pasteur"
    url = "https://research.pasteur.fr/en/member/luc-blassel/"
    pre = '<i class="fas fa-briefcase"></i>'

  [[menu.socials]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/luc-blassel/"
    pre = '<i class="fab fa-linkedin"></i>'

  [[menu.socials]]
    name = "ORCID"
    url = "https://orcid.org/0000-0002-6598-7673"
    pre = '<i class="fab fa-orcid"></i>'

  [[menu.socials]]
    name = "Google Scholar"
    url = "https://scholar.google.fr/citations?user=RYs6rFwAAAAJ&hl=en&oi=ao"
    pre = '<i class="fas fa-graduation-cap"></i>'

  [[menu.socials]]
    name = "Twitter"
    url = "https://twitter.com/lucblassel"
    pre = '<i class="fab fa-twitter"></i>'

  [[menu.socials]]
    name = "Contact me"
    url = "/contact/"
    pre = '<i class="fas fa-envelope"></i>'